version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      # This persists Composer's cache between container restarts
      # This means Composer doesn't have to re-download packages every time the container restarts
      # Significantly speeds up subsequent composer install or composer update commands
      - /var/cache/composer # Composer Cache [See Anonymous Volumes]
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=${XDEBUG_PORT}
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_LOG=/tmp/xdebug.log
      - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
      - XDEBUG_DISCOVER_CLIENT_HOST=true
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "${WP_HTTP_PORT}:80"
      - "${WP_HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/certs/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./docker/certs/localhost.key:/etc/ssl/private/localhost.key:ro
    depends_on:
      - php

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db-data:/var/lib/mysql
  theme:
    build:
      context: .
      dockerfile: docker/theme/Dockerfile
      # these are build-time arguments used by the Dockerfile
      args:
        WP_THEME_NAME: ${WP_THEME_NAME}
        # change this to the version of sage you want to install in the .env file
        SAGE_VERSION: ${SAGE_VERSION}
        WP_ENV: ${WP_ENV}
    volumes:
      #- .:/var/www/html
      # this is the directory where the theme is installed so changes made to files
      # on the host are reflected in the container
      - ./web/app/themes/${WP_THEME_NAME}:/var/www/html/web/app/themes/${WP_THEME_NAME}
      # container’s node_modules directory is isolated from your host system, 
      # preventing permission issues and avoiding polluting your local filesystem 
      # with container-built modules.
      - /var/www/html/web/app/themes/${WP_THEME_NAME}/node_modules
    environment:
      - WP_THEME_NAME=${WP_THEME_NAME}
      - SAGE_VERSION=${SAGE_VERSION}
      - WP_ENV=${WP_ENV}
    depends_on:
      - php
    # Optionally, run and exit after setup (no long-running process needed)
    command: ["true"]

  vite:
    image: node:18
    working_dir: /var/www/html/web/app/themes/${WP_THEME_NAME}
    command: npm run dev
    volumes:
      - .:/var/www/html
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    depends_on:
      - php
      - theme
volumes:
  db-data:
