version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=${XDEBUG_PORT}
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_LOG=/tmp/xdebug.log
      - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
      - XDEBUG_DISCOVER_CLIENT_HOST=true
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "${WP_HTTP_PORT}:80"
      - "${WP_HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/certs/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./docker/certs/localhost.key:/etc/ssl/private/localhost.key:ro
    depends_on:
      - php

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db-data:/var/lib/mysql

  vite:
    image: node:18
    working_dir: /var/www/html/web/app/themes/${WP_THEME_NAME}
    command: npm run dev
    volumes:
      - .:/var/www/html
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    depends_on:
      - php

volumes:
  db-data:
