version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9010:9010"
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_PORT=9010
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8181:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/certs/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./docker/certs/localhost.key:/etc/ssl/private/localhost.key:ro
    depends_on:
      - php

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  vite:
    image: node:18
    working_dir: /var/www/html/web/app/themes/impetus
    command: npm run dev
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - php
