version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/ssl/certs
    depends_on:
      - php

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  vite:
    image: node:18
    working_dir: /var/www/html/web/app/themes/impetus
    command: npm run dev
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - php
