name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check commits for GPG signatures
        run: |
          unsigned_commits=$(git log origin/${{ github.base_ref }}..HEAD --pretty="%H %G?" | grep -v 'G$' || true)
          if [ -n "$unsigned_commits" ]; then
            echo "❌ Found unsigned commits:"
            echo "$unsigned_commits"
            exit 1
          else
            echo "✅ All commits are signed!"
          fi
      - name: Check .gitignore syntax
        run: |
          if grep -P '[\r]' .gitignore; then
            echo "❌ ERROR: .gitignore contains Windows-style line endings (CRLF). Use LF only."
            exit 1
          fi

      - name: Validate .gitignore exists and is non-empty
        run: |
          if [ ! -s ".gitignore" ]; then
            echo "❌ ERROR: .gitignore is missing or empty!"
            exit 1
          fi
          echo "✅ .gitignore looks good."
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install Composer deps
        run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      - name: Lint PHP
        run: composer run-script lint
      - name: Run PHPUnit tests
        run: composer run-script test
