name: Database Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      # must be set in the repo secrets in repo settings > Secrets and Variables > Actions
      # Yes, you are duplicating the env vars here, but it's a small price to pay for the
      # ability to run the backup without having to have the .env file checked into the repo.
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

      # these are required for the WordPress container to start since we use them in the docker-compose.yml file
      # but they are not needed for the DB backup. You could split the docker-compose.yml file into two files
      # and have a separate workflow for starting the WordPress container, but this is simpler.
      XDEBUG_PORT: 9025
      XDEBUG_IDEKEY: CURSOR
      WP_HTTP_PORT: 8181
      WP_HTTPS_PORT: 8443
      WP_THEME_NAME: impetus
      VITE_PORT: 5173

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose
        run: docker compose up -d db

      - name: Wait for DB to be ready
        run: sleep 15

      - name: Export Database
        run: ./scripts/backup-db.zsh

      - name: Upload Database Backup
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: backup/
          retention-days: 7
